<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Chess.Core\Chess.Core.csproj" />
        <ProjectReference Include="..\Chess.Analysis\Chess.Analysis.csproj" />
        <ProjectReference Include="..\Chess.Stockfish\Chess.Stockfish.csproj" />
        <ProjectReference Include="..\Chess.Uci\Chess.Uci.csproj" />
        <ProjectReference
            Include="..\Chess.Variants.Standard\Chess.Variants.Standard.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Assets\**\*" />
    </ItemGroup>

</Project>
